### ISSUE TITLE
License installed in hardcoded path

### ISSUE THREAD

**Issue by leenaars** [arrufat/pdftag#1]
Hi Adrià,

"merci beaucoup" for pdftag - very useful. One issue: in meson.build, the path you use for storing the license is hardcoded. In not all distro's this is a suitable place, and it would make most sense to install this in the path the user set with --prefix.

Reason I'm asking is that I've packaged pdftag for Nixos:

https://github.com/NixOS/nixpkgs/pull/45666

In NixOS (and probably other distro's too) there is not such a path, making the build fail. So I manually have to patch the meson.build ...

**Comment by arrufat** [comment]
Hi, Thanks for contacting me. I currently do not have access to my development machine. I will fix it then (maybe in around 10 days, sorry about that)
